spring.application.name=reference-data-service

spring.profiles.active=dev

server.port=8036
server.servlet.context-path=/reference-data-service

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create

spring.cloud.gateway.discovery.locator.enabled=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

logging.level.org.springframework.web=DEBUG
logging.level.root=ERROR
logging.level.org.hibernate= DEBUG
logging.level.app.g_agent.contact=DEBUG

#hibernate to use UTC
spring.jpa.hibernate.jdbc.time_zone=UTC


# JWT Configuration
security.jwt.secret-key=f77109f4bc6a501e1ef2283c3a18ccd4e0054990e71d42294615c4c30ef755fc